name: publish-this-npm-package
on:
  push:
    tags:
      - "v*"

jobs:
  Test-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Run Test
        run: npx vitest run

      - name: Set version from tag
        run: npm version ${{ github.ref_name }} --no-git-tag-version

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
